<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<!-- NuGet packages -->
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.10" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.10" />
	</ItemGroup>

	<!-- Project reference -->
	<ItemGroup>
		<ProjectReference Include="..\BEWebshop.Core\BEWebshop.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BEWebshop.Core\BEWebshop.Core.csproj" />
	</ItemGroup>

</Project>
